<?php
session_start();
if (!isset($_SESSION["user"]) || $_SESSION['usertype'] != 'a') {
    header("location: ../login.php");
    exit();
}

include("../connection.php");

date_default_timezone_set('Asia/Kuala_Lumpur');
$today = date("Y-m-d H:i:s");

$doctorRes = $database->query("SELECT * FROM doctor");
$patientRes = $database->query("SELECT * FROM patient");
$appointmentRes = $database->query("SELECT * FROM appointment INNER JOIN patient ON appointment.pid=patient.pid INNER JOIN schedule ON appointment.scheduleid=schedule.scheduleid INNER JOIN doctor ON schedule.docid=doctor.docid");
$scheduleRes = $database->query("SELECT * FROM schedule INNER JOIN doctor ON schedule.docid=doctor.docid");
?>
<!DOCTYPE html>
<html>
<head>
    <title>System Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1, h2 { color: #2c3e50; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 40px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; font-size: 14px; }
        th { background-color: #f2f2f2; }
        .section { margin-top: 40px; }
        .summary-table td { font-weight: bold; }
    </style>
</head>
<body>

<h1>Klinik AzZahra Registration And Appointment System - Full System Report</h1>
<p>Generated on: <?php echo $today; ?></p>
<hr>

<h2>1. System Summary</h2>
<table class="summary-table">
    <tr><td>Total Doctors</td><td><?php echo $doctorRes->num_rows; ?></td></tr>
    <tr><td>Total Patients</td><td><?php echo $patientRes->num_rows; ?></td></tr>
    <tr><td>Total Appointments</td><td><?php echo $appointmentRes->num_rows; ?></td></tr>
    <tr><td>Total Sessions</td><td><?php echo $scheduleRes->num_rows; ?></td></tr>
</table>

<div class="section">
<h2>2. Doctor List</h2>
<table>
    <tr><th>Name</th><th>Email</th><th>NIC</th><th>Telephone</th><th>Specialties</th></tr>
    <?php while ($doc = $doctorRes->fetch_assoc()) {
        $speId = $doc['specialties'];
        $speName = $database->query("SELECT sname FROM specialties WHERE id='$speId'")->fetch_assoc()['sname'];
        echo "<tr><td>{$doc['docname']}</td><td>{$doc['docemail']}</td><td>{$doc['docnic']}</td><td>{$doc['doctel']}</td><td>$speName</td></tr>";
    } ?>
</table>
</div>

<div class="section">
<h2>3. Patient List</h2>
<table>
    <tr><th>Name</th><th>Email</th><th>NIC</th><th>Telephone</th><th>Date of Birth</th><th>Address</th></tr>
    <?php while ($pat = $patientRes->fetch_assoc()) {
        echo "<tr><td>{$pat['pname']}</td><td>{$pat['pemail']}</td><td>{$pat['pnic']}</td><td>{$pat['ptel']}</td><td>{$pat['pdob']}</td><td>{$pat['paddress']}</td></tr>";
    } ?>
</table>
</div>

<div class="section">
<h2>4. Appointment Records</h2>
<table>
    <tr><th>Appointment No</th><th>Patient</th><th>Doctor</th><th>Session</th><th>Date</th><th>Time</th></tr>
    <?php while ($app = $appointmentRes->fetch_assoc()) {
        echo "<tr><td>{$app['apponum']}</td><td>{$app['pname']}</td><td>{$app['docname']}</td><td>{$app['title']}</td><td>{$app['appodate']}</td><td>{$app['scheduletime']}</td></tr>";
    } ?>
</table>
</div>

<div class="section">
<h2>5. Scheduled Sessions</h2>
<table>
    <tr><th>Session Title</th><th>Doctor</th><th>Date</th><th>Time</th><th>Max Patients</th></tr>
    <?php while ($ses = $scheduleRes->fetch_assoc()) {
        echo "<tr><td>{$ses['title']}</td><td>{$ses['docname']}</td><td>{$ses['scheduledate']}</td><td>{$ses['scheduletime']}</td><td>{$ses['nop']}</td></tr>";
    } ?>
</table>
</div>

<p style="text-align: center; font-size: 13px; color: #999;">Generated by Klinik AzZahra Registration And Appointment System | <?php echo date("Y"); ?></p>

<button onclick="window.print()" class="btn-primary btn" style="float:right; margin: 20px;">🖨️ Print / Save as PDF</button>


</body>
</html>
